"""Pure-standard-library text extraction from PDFs.

There is no PDF library available (and requiring one would mean asking every
user to run pip), so this reads the file structure directly: it inflates the
FlateDecode content streams and walks the text-showing operators inside them.

This works on PDFs generated by software — which is what purchase orders,
invoices and order confirmations out of an ERP always are. It does NOT work
on scanned paper, which holds pictures of words and needs OCR; those files
are still stored and stay searchable by filename, company and order.

If the `pdftotext` binary happens to be installed, it is used instead, since
it handles awkward font encodings better.
"""

import re
import shutil
import subprocess
import zlib

# String literal, hex string, or an operator we care about.
_TOKEN_RE = re.compile(
    rb"""
      \((?P<lit>(?:\\.|[^()\\]|\((?:\\.|[^()\\])*\))*)\)   # (literal string)
    | <(?P<hex>[0-9A-Fa-f\s]*)>                            # <hex string>
    | (?P<num>-?\d+(?:\.\d+)?)                             # number
    | (?P<op>T[JjdDfm*wLscz]|'|\"|BT|ET|Td|TD|TL|Tstar)    # operator
    """,
    re.VERBOSE,
)

_ESCAPES = {
    ord("n"): b"\n", ord("r"): b"\r", ord("t"): b"\t",
    ord("b"): b"\b", ord("f"): b"\f",
    ord("("): b"(", ord(")"): b")", ord("\\"): b"\\",
}


def _unescape(raw: bytes) -> bytes:
    """Resolve PDF literal-string escape sequences."""
    out = bytearray()
    i = 0
    n = len(raw)
    while i < n:
        ch = raw[i]
        if ch != 0x5C:  # backslash
            out.append(ch)
            i += 1
            continue
        i += 1
        if i >= n:
            break
        nxt = raw[i]
        if nxt in _ESCAPES:
            out += _ESCAPES[nxt]
            i += 1
        elif 0x30 <= nxt <= 0x37:  # octal, up to three digits
            digits = bytearray()
            while i < n and len(digits) < 3 and 0x30 <= raw[i] <= 0x37:
                digits.append(raw[i])
                i += 1
            out.append(int(digits, 8) & 0xFF)
        elif nxt in (0x0A, 0x0D):  # line continuation
            i += 1
            if i < n and raw[i] == 0x0A and nxt == 0x0D:
                i += 1
        else:
            out.append(nxt)
            i += 1
    return bytes(out)


def _decode_string(data: bytes) -> str:
    """Turn raw PDF string bytes into text, guessing the encoding."""
    if not data:
        return ""
    # UTF-16BE byte-order mark, or the every-other-byte-is-zero pattern that
    # two-byte CID encodings produce.
    if data[:2] == b"\xfe\xff":
        return data[2:].decode("utf-16-be", "replace")
    if len(data) >= 4 and len(data) % 2 == 0 and data[0::2].count(0) > len(data) // 4:
        try:
            return data.decode("utf-16-be", "replace")
        except Exception:
            pass
    return data.decode("latin-1", "replace")


def _text_from_content(content: bytes) -> str:
    """Walk one content stream and pull out the shown text."""
    pieces = []
    pending_nums = []
    for m in _TOKEN_RE.finditer(content):
        if m.group("lit") is not None:
            pieces.append(("s", _decode_string(_unescape(m.group("lit")))))
            pending_nums = []
        elif m.group("hex") is not None:
            raw = re.sub(rb"\s", b"", m.group("hex"))
            if len(raw) % 2:
                raw += b"0"
            try:
                pieces.append(("s", _decode_string(bytes.fromhex(raw.decode("ascii")))))
            except ValueError:
                pass
            pending_nums = []
        elif m.group("num") is not None:
            pending_nums.append(float(m.group("num")))
        else:
            op = m.group("op")
            if op in (b"Td", b"TD", b"T*", b"Tstar"):
                pieces.append(("nl", "\n"))
            elif op == b"TJ":
                # Kerning numbers inside a TJ array; a big negative shift is
                # how PDFs usually render a word space.
                pass
            elif op in (b"'", b'"'):
                pieces.append(("nl", "\n"))
            pending_nums = []

    out = []
    for kind, value in pieces:
        out.append(value)
    text = "".join(out)
    return text


def _kerned_spaces(content: bytes) -> bytes:
    """Insert a space where a TJ array uses a wide negative kern.

    Done as a byte-level pre-pass so the main tokeniser stays simple.
    """
    def repl(m):
        return b"(" + b" " + b")" if float(m.group(1)) < -180 else b""
    return re.sub(rb"(?<=\))\s*(-?\d+(?:\.\d+)?)\s*(?=\()", repl, content)


def _iter_streams(data: bytes):
    """Yield the decoded bytes of every content stream in the file."""
    for m in re.finditer(rb"stream\r?\n", data):
        start = m.end()
        end = data.find(b"endstream", start)
        if end == -1:
            continue
        raw = data[start:end].rstrip(b"\r\n")

        # The object dictionary sits just before the `stream` keyword.
        head_start = max(0, m.start() - 600)
        head = data[head_start:m.start()]
        if b"/Image" in head or b"/DCTDecode" in head or b"/JPXDecode" in head:
            continue

        if b"/FlateDecode" in head:
            try:
                yield zlib.decompress(raw)
                continue
            except zlib.error:
                try:  # truncated or slightly malformed streams are common
                    yield zlib.decompressobj().decompress(raw)
                    continue
                except zlib.error:
                    continue
        elif b"/Filter" in head:
            continue  # some other compression we cannot undo
        else:
            yield raw


def _printable_ratio(text: str) -> float:
    if not text:
        return 0.0
    good = sum(1 for ch in text if ch.isalnum() or ch.isspace() or ch in ".,:;/-()#&%$@'\"+*=[]")
    return good / len(text)


def _via_pdftotext(path) -> str | None:
    """Use the pdftotext binary when the machine happens to have it."""
    exe = shutil.which("pdftotext")
    if not exe:
        return None
    try:
        res = subprocess.run(
            [exe, "-layout", "-enc", "UTF-8", str(path), "-"],
            capture_output=True, timeout=60,
        )
        if res.returncode == 0:
            return res.stdout.decode("utf-8", "replace")
    except (subprocess.SubprocessError, OSError):
        pass
    return None


def extract(path) -> tuple[str, str]:
    """Return (text, note). An empty text with a note means "not readable"."""
    external = _via_pdftotext(path)
    if external and external.strip():
        return _tidy(external), "extracted with pdftotext"

    try:
        data = path.read_bytes()
    except OSError as exc:
        return "", f"could not read file: {exc}"

    chunks = []
    for content in _iter_streams(data):
        if b"BT" not in content and b"Tj" not in content and b"TJ" not in content:
            continue
        chunks.append(_text_from_content(_kerned_spaces(content)))

    text = _tidy("\n".join(chunks))
    if not text.strip():
        return "", "no text layer — likely a scan; searchable by filename only"
    if _printable_ratio(text) < 0.55:
        return text, "text layer uses a custom font encoding; extraction is partial"
    return text, ""


def _tidy(text: str) -> str:
    """Collapse the whitespace noise that extraction always produces."""
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = re.sub(r"[ \t\x00]+", " ", text)
    text = re.sub(r" *\n *", "\n", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()
